### ISSUE TITLE
Amazon Interview Questions

### ISSUE THREAD

**Issue by skystone1000** [kamyu104/LeetCode-Solutions#103]
Hey Hii,
Do you have leetcode Premium subscription?

I just wanted the List of top Amazon questions in that in
Explore -> Top Amazon Questions Card

Can you Please Help me, I have Amazon Interview next week.
It would be very helpful if you could add a section for that.

Thanks in advance

**Comment by kamyu104** [comment]
You can just subscribe to Leetcode Premium for a short time.
It would be very helpful for your interview preparation. :)
