### ISSUE TITLE
Wrong answer for Integer to Roman in Python

### ISSUE THREAD

**Issue by prakharrathi25** [kamyu104/LeetCode-Solutions#122]
I ran the test cases using the code given on the repo and the answers are incorrect for multiple test cases. I am attaching a screenshot below. 

![image](https://user-images.githubusercontent.com/38958532/102596072-a495f180-413e-11eb-941f-5b956d669ec3.png)

Creating a pull request to replace the incorrect output with my solution which works on all test cases.

**Comment by kamyu104** [comment]
In fact, the solutions in this repository only work in`Python2`.
In `Python2`, the `/ `operator is integer division if inputs are integers.
So if you want to run it in `Python3`, you need some modification.
Thanks for your friendly reminder.
