### ISSUE TITLE
[Question] 0424 Longest repeating character replacement: Space complexity

### ISSUE THREAD

**Issue by iamrudra** [kamyu104/LeetCode-Solutions#130]
I am relatively new to python so kindly pardon me if my understanding is off. With that said, I wanted to confirm if the space complexity of your solution would still be O(1). 

~It seems to me that you are using the count variable (an object of the Counter class) to essentially keep a track of character frequency. Wouldn't that make the space complexity O(n)?~

My bad, did not realize that n being 26, it is effectively O(n) = O(26)=> O(1)

**Comment by iamrudra** [comment]
Created [a PR](https://github.com/kamyu104/LeetCode-Solutions/pull/131) in case you deem this valid.

**Comment by kamyu104** [comment]
Yes, the space is the count of alphabet letters from the input string. So it is `O(26) = O(1)`.
