### ISSUE TITLE
How to explain totalCount, validCountInLessLength, validCountInFullLength in confusing-number-ii.py?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [kamyu104/LeetCode-Solutions#133]
How to explain `totalCount`, `validCountInLessLength`, `validCountInFullLength` in [`confusing-number-ii.py`](https://github.com/kamyu104/LeetCode-Solutions/blob/master/Python/confusing-number-ii.py)?

**Comment by kamyu104** [comment]
- `totalCount` : count of all numbers in the pattern of `[01689]{1,len(str(n))}` in the range of [1, n]
- `validCountInLessLength` :  count of unconfused numbers in the pattern of `[01689]{1,len(str(n))-1}` in the range of [1, n]
- `validCountInFullLength` :  count of unconfused numbers in the pattern of `[01689]{len(str(n))}` in the range of [1, n]
- Take `n = 20` as an example:
    - `totalCount` :  len([1, 6, 8, 9, 10, 11, 16, 18, 19]) = 9
    - `validCountInLessLength` : len([1, 8]) = 2
    - `validCountInLessLength` : len([11]) = 1
    - The answer is (`totalCount` - `validCountInLessLength` -  `validCountInFullLength`) = 9 - 2 - 1 = 6

**Comment by yezhengli-Mr9** [comment]
Any reference for explaining`validCountInFullLength(...)`? Your explanation makes sense except for trivial correction (of '0' should appear in both `totalCount(...)` and `validCountInLessLengthv`):
```python
N 20 totalCountN 10 validCountInLessLengthN 3 validCountInFullLengthN 0
N 100 totalCountN 26 validCountInLessLengthN 7 validCountInFullLengthN 0
N 95 totalCountN 22 validCountInLessLengthN 3 validCountInFullLengthN 0
N 150 totalCountN 35 validCountInLessLengthN 7 validCountInFullLengthN 1
N 195 totalCountN 47 validCountInLessLengthN 7 validCountInFullLengthN 2
N 200 totalCountN 50 validCountInLessLengthN 7 validCountInFullLengthN 3
```

**Comment by kamyu104** [comment]
The valid range of n is `[1, 10^9]`, so '0' is invalid and should be excluded in all 3 functions.
If you want to count it, just make some modifications.
