### ISSUE TITLE
What happened to your old Leetcode repository

### ISSUE THREAD

**Issue by XtraSonic** [kamyu104/LeetCode-Solutions#136]
Hello,
Sorry for opening an issue here, but I didn't know how else I could ask you this question. 

I recently found out about leetcode and I challenged myself to solve at least one problem each day (from the free version for now). I also decided to store my work on github along with a readme in which I put both the text of the problem and how I went about solving it (mostly for my future reference). I was sure I was not the first one to come up with the idea of having the solutions on github and I wanted to see how other people structured their repository and that's how I found yours.

I noticed that in your README you you said "R.I.P. to my old Leetcode repository, where there were 5.7k+ stars and 2.2k+ forks (ever the top 3 in the field). Since free questions may be even mistakenly taken down by some companies, only solutions will be post on now." My aim is not to get stars or forks, but I did want to save the text of the problems that I solved next to my thoughts in order to have everything in one place so I wanted to ask: 

Was your previous repo taken down solely because of the text of a problem (which is also publicly available for free on Leetcode as well) or were there other things that lead to the termination of that repo? Also, what would you recommend, should I stop saving the text of the problems ?

**Comment by kamyu104** [comment]
- In the past, the free public problem descriptions on Leetcode may have been copied directly from some copyright-protected online interview sites.
- If you paste the whole problem description without knowing the source of the whole problem description,. Even if only the short description is the same, the copyright website will submit a DMCA complaint and delete your entire repository without warning.
- The good news is that Github will give repository owners a chance to make changes before processing the DMCA takedown notice, and there is less chance of encountering this problem. You can see [Github DMCA](https://github.com/github/dmca).
- I still suggest you don’t put the original problem description on it to avoid this problem. Maybe you can put a modified / simplified one.
- Happy coding every day. 👍

**Comment by XtraSonic** [comment]
Thank you very much for all the information :D
