### ISSUE TITLE
around 600-800 files truncated means they are lost?

### ISSUE THREAD

**Issue by vandit2209** [kamyu104/LeetCode-Solutions#139]
If not lost, subdivide it into folders so that it is visible on the repo.

**Comment by kamyu104** [comment]
It is a folder display problem on Github. A folder on the webpage can only display 1000 files without pagination. You can access them through README.md.

**Comment by vandit2209** [comment]
subdivide in more folders may be?

**Comment by vandit2209** [comment]
that would be of great help

**Comment by kamyu104** [comment]
Thanks for your suggestion, but I have no plans to do so at the moment, because it is not necessary and takes time.
