### ISSUE TITLE
Can someone explain what this line of code means? TIA!

### ISSUE THREAD

**Issue by indraneelpatil** [kamyu104/LeetCode-Solutions#141]
https://github.com/kamyu104/LeetCode-Solutions/blob/bd9eabcffedba0fadc0a9a96c61f08128cecd1cf/C%2B%2B/increasing-triplet-subsequence.cpp#L12

Is this equivalent to two separate lines like :

- a=min;
- b=c;

**Comment by RanceJen** [comment]
Yes, it does.

**Comment by indraneelpatil** [comment]
Okay thanks!
