### ISSUE TITLE
Shouldn't this be p[0] -= times?

### ISSUE THREAD

**Issue by GUOWEICAIUS** [kamyu104/LeetCode-Solutions#150]
https://github.com/kamyu104/LeetCode-Solutions/blob/5ef49a494bcf7ee966f03a647dfb75a39900df9e/Python/design-search-autocomplete-system.py#L29

**Comment by kamyu104** [comment]
No, `times` is the latest value instead of delta value.

**Comment by GUOWEICAIUS** [comment]
Thanks. That's correct because we are recording the time of s, not the prefix to the current Trie node (which would be accumulated value then).
