### ISSUE TITLE
Amzone intrvw solution help

### ISSUE THREAD

**Issue by lightupcode** [kamyu104/LeetCode-Solutions#152]
Kamyu104, thank you so much for your past help and can you help me with the below question.

I have attached the question as well.

Problem:

Contiguous array groups sum of below formula.

Formula is : power = min( array[i]) * sum(array[i])

Input array : [2,3,2,1]

Output: 69

Contiguous subarrays are: array[0,0], array[0,1], [0,2], [0,3], [1,1], [1,2], [1,3], [2,2], [2,3] and [3,3]
Code: Naïve Approach below

But need a faster and optimal solution.

def findTotalPower(power):
n = len(power)
Total_sum = 0
Total_power_list = []
for i in range(n):
for j in range(i , n):
temp_list = power[i : 1+j]
tot = min(temp_list) * sum(temp_list)
Total_power_list.append(tot)
Total = sum(Total_power_list)
Total = (Total % (10**9 + 7))
return Total

![A_Q_2_1](https://user-images.githubusercontent.com/99361948/153281418-fc170bf7-75e9-4161-85ce-0b6a4ad2289b.jpg)
[A_Q_2_6.txt](https://github.com/kamyu104/LeetCode-Solutions/files/8035852/A_Q_2_6.txt)
![A_Q_2_5](https://user-images.githubusercontent.com/99361948/153281443-b56b33e0-2e66-41db-a165-b99bea42dc8a.jpg)
![A_Q_2_4](https://user-images.githubusercontent.com/99361948/153281453-d6b780ae-f35c-4c44-aae1-b6223051768e.jpg)
![A_Q_2_3](https://user-images.githubusercontent.com/99361948/153281463-85e6e7a7-2e23-45b0-9102-b9eb92598b83.jpg)
![A_Q_2_2](https://user-images.githubusercontent.com/99361948/153281472-0755c0f7-c647-4974-a906-655c69abf70c.jpg)

**Comment by kamyu104** [comment]
- I don't think this repo is suitable for discussing your interview questions.
- You can post your questions on the Leetcode forum.
- Many people there will be interested in discussing them.
- I'll delete it first.
