### ISSUE TITLE
336 palindrome pairs Time limit exceed(C++)

### ISSUE THREAD

**Issue by sparshgarg23** [kamyu104/LeetCode-Solutions#156]
Getting TLE exceeded for the following input
https://leetcode.com/submissions/detail/706759598/testcase/

**Comment by kamyu104** [comment]
Fixed in the [commit](https://github.com/kamyu104/LeetCode-Solutions/commit/05ee4ae8cd9c6bfc6284477126006045c1ab0348). Thanks for notification.
