### ISSUE TITLE
1558 the [0] case could not passed

### ISSUE THREAD

**Issue by ljhust** [kamyu104/LeetCode-Solutions#162]
the [0] case not passed, resolve this problem below:

class Solution:
    def minOperations(self, nums: List[int]) -> int:
        def popcount(num):
            result = 0
            while num:
                num &= num - 1
                result += 1
            return result
        result, max_len = 0, 0
        if len(nums) == 1 and nums[0] == 0:
            return 0
        else:
            for num in nums:
                result += popcount(num)
                max_len = max(max_len, num.bit_length())
            return result + max_len -1

**Comment by kamyu104** [comment]
Fixed. Thank you for the notification.
