### ISSUE TITLE
Leetcode 2511 - Fix xrange

### ISSUE THREAD

**Issue by nitinraturi** [kamyu104/LeetCode-Solutions#182]
Python3 error: https://github.com/kamyu104/LeetCode-Solutions/blob/a26137e344650ff9317bac61fa7fe47a49f39f3b/Python/maximum-enemy-forts-that-can-be-captured.py#L12

Change `xrange` to `range`.

**Comment by kamyu104** [comment]
The solutions of this repository are mainly written in Python2.
In Python 3, there is no xrange , but the range function behaves like xrange in Python2.
You can replace it yourself if you want to run in Python3.
