### ISSUE TITLE
Improve Handling of Negative Numbers in alternateDigitSum

### ISSUE THREAD

**Issue by Mahi3454** [kamyu104/LeetCode-Solutions#195]
@kamyu104  
The alternateDigitSum function has several issues that need fixing. It doesn't handle negative inputs, which can cause incorrect results; we should add a check for negatives, possibly returning an error or using their absolute value. The variable sign is ambiguous and should be renamed to alternateSign for clarity. The code lacks comments explaining its logic, especially the loop's purpose and how the alternate digit sum is calculated. Additionally, unit tests should be added to cover edge cases like single-digit and large integers. Finally, while the function correctly returns 0 for n = 0, this should be explicitly mentioned in the comments.
// Time:  O(logn)
// Space: O(1)

// math
class Solution {
public:
    int alternateDigitSum(int n) {
        int result = 0, sign = 1;
        for (; n; n /= 10) {
            sign *= -1;
            result += sign * (n % 10);
        }
        return sign * result;
    }
};
To fix the issues in the alternateDigitSum function, we will check for negative numbers and either use their absolute value or return an error. We'll rename sign to alternateSign for clarity. Comments will be added to explain what the code does, including how the alternate digit sum is calculated. We'll also create tests for positive and negative numbers, single digits, zero, and large numbers. Lastly, we'll update the documentation to reflect these changes.

**Comment by kamyu104** [comment]
Thank you for the feedback. However, the problem constraints guarantee only non-negative inputs, so handling negatives isn't necessary.
