### ISSUE TITLE
why is it linear?

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode-Solutions#23]
https://github.com/kamyu104/LeetCode-Solutions/blob/18a7807c127eae36792452df13f255b0ee88f72b/Python/wildcard-matching.py#L18
Seems it is DFS, every time you first match a '*' with empty string. When facing trouble, you trace back to
match it with one char, and so on. Why is it linear?

**Comment by kamyu104** [comment]
Yes, you are right. It should be `Time: O(m * n), Space: O(1)`.
