### ISSUE TITLE
A question regarding combination-sum.py

### ISSUE THREAD

**Issue by gxstudy** [kamyu104/LeetCode-Solutions#3]
Hi, kamyu, 

Thanks a lot for providing these awesome solutions, this is actually a question instead of an issue, and I am sorry I put it here since I didn't find any other way to leave a message to you. If you want me to move this somewhere else, I am totally glad to do. 

I am wondering why "result.append(intermediate)" in the code doesn't give the right result. I printed out intermediate every time before appending to result and confirmed that it's a list. But inserting it without the list() function gives the wrong result. 

```
class Solution(object):
    def combinationSum(self, candidates, target):
        result = []
        self.combinationSumRecu(sorted(candidates), result, 0, [], target)
        return result

    def combinationSumRecu(self, candidates, result, start, intermediate, target):
        if target == 0:
            result.append(list(intermediate))
            #why result.append(intermediate) doesn't give the right result? 
        while start < len(candidates) and candidates[start] <= target:
            intermediate.append(candidates[start])
            self.combinationSumRecu(candidates, result, start, intermediate, target - candidates[start])
            intermediate.pop()
            start += 1
```
Thanks a lot for your help. 

Best,
Cindy

**Comment by kamyu104** [comment]
* `intermediate` here is a reference
* You need to make a copy of `intermediate` into the result
* Otherewise, it would be modified durring the recurrsuion.

**Comment by gxstudy** [comment]
Thanks a lot.
