### ISSUE TITLE
overflow issue

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode-Solutions#37]
https://github.com/kamyu104/LeetCode-Solutions/blob/34079035f7cebb9740fe4f4edb70e0e9d3625c2d/C%2B%2B/palindrome-number.cpp#L16

How do you make sure that if the reversed integer overflows, the result must not equal the input. I mean,
maybe 12345999999 --reverse--> 99999954321 ---overflow---> 12345999999, and this is just an example.
My question is how do you know this kind of numbers do not exist.

**Comment by kamyu104** [comment]
Yes, you are right. We should check if it overflows or not. The solution has been updated. Thanks!
