### ISSUE TITLE
Could you tell me the reason why we need `board[x][y] = 'V'` in surrounded-regions.py

### ISSUE THREAD

**Issue by sangheestyle** [kamyu104/LeetCode-Solutions#39]
Hi,

I have a question for a solution at the following link:

https://github.com/kamyu104/LeetCode-Solutions/blob/b55ed99a0b8d07bb14085dd3577c600c5a98c439/Python/surrounded-regions.py#L31

Line 31 has `board[x][y] = 'V'` even we mardked board[i][j] = 'V' at line 27. Either way is fine for OJ but could you tell me why we need line 31?

**Comment by kamyu104** [comment]
Yes, you are right. It's not necessary. I've updated the solution. Thank you very much.
