### ISSUE TITLE
The Python solution of 685 Redundant Connection II might need to be improved.

### ISSUE THREAD

**Issue by sangheestyle** [kamyu104/LeetCode-Solutions#5]
Hi,

It seems that the Python solution of 685 Redundant Connection II might need to be improved because it doesn't work.

I wanted to contribute to the solution but I am still trying to solve the problem. :0

**Comment by kamyu104** [comment]
Thanks for notification. This has been fixed :).

**Comment by sangheestyle** [comment]
@kamyu104 Awesome. I checked the solution and easy to expand from your UnionFind solutions.

Additionally, can I ask you a question?

Could you tell me the reason why we need `y != y_root`? Without it, it looks fine but I am wondering.

**Comment by kamyu104** [comment]
Because we have skipped the edge which makes 2 parents.

**Comment by sangheestyle** [comment]
@kamyu104 I checked it. Thank you so much!
