### ISSUE TITLE
index array might be not in ascending order

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode-Solutions#69]
https://github.com/kamyu104/LeetCode-Solutions/blob/b7cfbdf0f5368ac1efac07fed0e4d6eb507d8f36/C%2B%2B/insert-delete-getrandom-o1-duplicates-allowed.cpp#L27
seems you think the tail element in the storage is corresponding to the tail element in the index array, which 
might be wrong after you do some swap

**Comment by kamyu104** [comment]
I fixed it. Thank you very much!
