### ISSUE TITLE
Time complexity is not O(n * 2 ^ n)

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode-Solutions#70]
https://github.com/kamyu104/LeetCode-Solutions/blob/7980b27daba9332caff1a6778fca499838a2313c/C%2B%2B/optimal-account-balancing.cpp#L35
this for loop can be at most O(2 ^ n) times

**Comment by kamyu104** [comment]
I fixed it. Thank you very much!
