### ISSUE TITLE
Problem #647 Palindromic Substrings

### ISSUE THREAD

**Issue by liadbiz** [kamyu104/LeetCode-Solutions#77]
Hi, your solutions are greet! 

But I can not understand your solution of problem #647, and it seems give wrong answer.

![image](https://user-images.githubusercontent.com/11924130/59699796-c4381b00-9224-11e9-8c0a-a593dd05afd9.png)

**Comment by kamyu104** [comment]
It works in python 2.
For python 3, you should change "/" into "//", thanks!

**Comment by liadbiz** [comment]
Fine. But could you please give some explanation of your solution? It's a little magic for me.

By the way, Would you consider updating your code to python3?

**Comment by kamyu104** [comment]
No, changing from python 2 to 3 is much easier than python 3 to 2.
