### ISSUE TITLE
Why is the complexity O(N^2) and not O(N)

### ISSUE THREAD

**Issue by sparshgarg23** [kamyu104/LeetCode-Solutions#87]
Hello,can you explain why the compexity is O(N^2) and not O(N)

**Comment by kamyu104** [comment]
I don't understand which problem you are asking about?
Could you give me more details?

**Comment by sparshgarg23** [comment]
Sure I will get back to you soon with the details

**Comment by sparshgarg23** [comment]
The problem is reverse substrings between each pair of parantheses(C++ )

**Comment by kamyu104** [comment]
According to **"1190. Reverse Substrings Between Each Pair of Parentheses"** :
*  I added a real **_O(n)_** solution from Leetcode forum. Each character is traversed only once.
* Thanks for your friendly reminder.
