### ISSUE TITLE
Another approach for intersection-of-two-arrays-ii.cpp 

### ISSUE THREAD

**Issue by git-hub-tig** [kamyu104/LeetCode-Solutions#91]
Thk you kamyu very much! Your work is incredible. I learned a lot.
below is my approach for intersection-of-two-arrays-ii.cpp 
```
#define be(x) begin(x), end(x)
class Solution {
public:
    vector<int> intersect(vector<int>& nums1, vector<int>& nums2) {
        vector<int> res;
        sort(be(nums1)); sort(be(nums2));
        set_intersection(be(nums1), be(nums2), back_inserter(res));
        return res;
    }
};
```

**Comment by git-hub-tig** [comment]
And another approach for intersection-of-two-arrays.cpp.
just base on code above, add new line
```
res.erase(unique(be(res)), end(res));
````
God bless you, Kamyu!!

**Comment by kamyu104** [comment]
I have added your solutions.
Thank you for your blessing and wish you all the best.
